SRC_LIB =		ft_bzero.s	 \
				ft_isalnum.s \
				ft_isalpha.s \
				ft_isascii.s \
				ft_isdigit.s \
				ft_isprint.s \
				ft_toupper.s \
				ft_tolower.s \
				ft_strlen.s	 \
				ft_puts.s	 \
				ft_strcat.s	 \
				ft_strncat.s \
				ft_memcpy.s	 \
				ft_memset.s	 \
				ft_strdup.s	 \
				ft_cat.s	 \
